accounts:
  - name: alice
    mnemonic: "slide moment original seven milk crawl help text kick fluid boring awkward doll wonder sure fragile plate grid hard next casual expire okay body"
    coins: ["200000000nois"]
  - name: bob
    mnemonic: "trap possible liquid elite embody host segment fantasy swim cable digital eager tiny broom burden diary earn hen grow engine pigeon fringe claim program"
    coins: ["200000000nois"]
  - name: carol
    mnemonic: "great immense still pill defense fetch pencil slow purchase symptom speed arm shoot fence have divorce cigar rapid hen vehicle pear evolve correct nerve"
    coins: ["200000000nois"]
  - name: dave
    mnemonic: "resist portion leisure lawn shell lunch inhale start pupil add fault segment hour dwarf toddler insect frame math remove twist easy paddle nice rhythm"
    coins: ["200000000nois"]
  - name: joe
    mnemonic: "diary behind allow lawn loop assault armor survey media toe rural mass skull way crater tobacco pair glare window soon lift pistol fitness annual"
    coins: ["200000000nois"]
  - name: steve
    mnemonic: "initial aisle blush gift shuffle hat solar dove dwarf soup credit acid update seed mercy thumb swear main verb image dove rose chat inmate"
    coins: ["200000000nois"]
  - name: olivia
    mnemonic: "dinosaur submit around jacket movie garden crash weather matter option time cabbage butter mind skin nature ride mosquito seat lock elephant merit empower come"
    coins: ["200000000nois"]
validator:
  name: alice
  staked: "100000000nois"
faucet:
  name: bob
  coins: ["100000nois"]
genesis:
  chain_id: nois
  app_state:
    bank:
      denom_metadata:
        - description: "The native staking token of Starport Network"
          display: "nois"
          base: "nois"
          name: "Starport Network"
          symbol: "nois"
          denom_units:
            - denom: "nois"
              aliases:
                - "micronois"
              exponent: "0"
            - denom: "mnois"
              aliases:
                - "millinois"
              exponent: "3"
            - denom: "nois"
              exponent: "6"
    staking:
      params:
        bond_denom: "nois"
    crisis:
      constant_fee:
        denom: "nois"
    gov:
      deposit_params:
        min_deposit:
          - "amount": "1"
            "denom": "nois"
    mint:
      params:
        mint_denom: "nois"
        distribution_proportions:
          staking: "0.300000000000000000"
          incentives: "0.400000000000000000"
          development_fund: "0.200000000000000000"
          community_pool: "0.100000000000000000"
        development_fund_recipients:
          - address: "nois1ezptsm3npn54qx9vvpah4nymre59ykr9exx2ul" # alice
            weight: "0.400000000000000000"
          - address: "nois1aqn8ynvr3jmq67879qulzrwhchq5dtrvtx0nhe" # bob
            weight: "0.300000000000000000"
          - address: "nois1pkdk6m2nh77nlaep84cylmkhjder3arey7rll5" # carol
            weight: "0.300000000000000000"
    launch:
      params:
        revertDelay: "5"
        launchTimeRange:
          minLaunchTime: "5"
    fundraising:
      params:
        auction_creation_fee:
          - amount: "100"
            denom: "nois"
    monitoringp:
      params:
        lastBlockHeight: "1"
        consumerChainID: "orbit-1"
        consumerUnbondingPeriod: "2"
        consumerRevisionHeight: "1"
    participation:
      params:
        allocationPrice:
          bonded: "1000"
        participationTierList:
          - tierID: "1"
            requiredAllocations: "1"
            benefits:
              maxBidAmount: "1000"
          - tierID: "2"
            requiredAllocations: "2"
            benefits:
              maxBidAmount: "2000"
          - tierID: "3"
            requiredAllocations: "5"
            benefits:
              maxBidAmount: "10000"
          - tierID: "4"
            requiredAllocations: "10"
            benefits:
              maxBidAmount: "30000"
        # represents 1/3 of the default unbonding period (21 days): one week
        registrationPeriod: "604800s"
        # represents 2/3 of the default unbonding period (21 days): two weeks
        withdrawalDelay: "1209600s"
    claim:
      airdropSupply:
        amount: "1000"
        denom: "drop"
      claimRecords:
        - address: "nois1ezptsm3npn54qx9vvpah4nymre59ykr9exx2ul" # alice
          claimable: "400"
        - address: "nois1aqn8ynvr3jmq67879qulzrwhchq5dtrvtx0nhe" # bob
          claimable: "500"
        - address: "nois1pkdk6m2nh77nlaep84cylmkhjder3arey7rll5" # carol
          claimable: "100"
      missions:
        - missionID: "0"
          description: "initial claim"
          weight: "0.2"
        - missionID: "1"
          description: "staking"
          weight: "0.5"
        - missionID: "2"
          description: "voting"
          weight: "0.3"
      initialClaim:
        enabled: true
        missionID: "0"
client:
  typescript:
    path: "ignite-ui/src/generated"
build:
  main: "cmd/noisd"  
